// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCWZrsfkUI20QMb0Me_muR4_6mFaGlEI',
    appId: '1:587807952921:web:62312811a0468597e5da88',
    messagingSenderId: '587807952921',
    projectId: 'whatsapp-flutter-d499c',
    authDomain: 'whatsapp-flutter-d499c.firebaseapp.com',
    storageBucket: 'whatsapp-flutter-d499c.appspot.com',
    measurementId: 'G-2BJZNSSXKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGNNl3QYPtQazkNIQTEPooVANJB9YgjE',
    appId: '1:587807952921:android:b91090827fd9f85ae5da88',
    messagingSenderId: '587807952921',
    projectId: 'whatsapp-flutter-d499c',
    storageBucket: 'whatsapp-flutter-d499c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYEyAYk3v4GXpoG8JjWGuyebOym4lo0y0',
    appId: '1:587807952921:ios:1e27a5c1512e53a0e5da88',
    messagingSenderId: '587807952921',
    projectId: 'whatsapp-flutter-d499c',
    storageBucket: 'whatsapp-flutter-d499c.appspot.com',
    iosBundleId: 'com.whatsappf.sj.whatsappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYEyAYk3v4GXpoG8JjWGuyebOym4lo0y0',
    appId: '1:587807952921:ios:1e27a5c1512e53a0e5da88',
    messagingSenderId: '587807952921',
    projectId: 'whatsapp-flutter-d499c',
    storageBucket: 'whatsapp-flutter-d499c.appspot.com',
    iosBundleId: 'com.whatsappf.sj.whatsappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUCWZrsfkUI20QMb0Me_muR4_6mFaGlEI',
    appId: '1:587807952921:web:35908e1c8115a1dfe5da88',
    messagingSenderId: '587807952921',
    projectId: 'whatsapp-flutter-d499c',
    authDomain: 'whatsapp-flutter-d499c.firebaseapp.com',
    storageBucket: 'whatsapp-flutter-d499c.appspot.com',
    measurementId: 'G-BF3GYXHK88',
  );
}
